# Generated by Django 3.2.5 on 2021-10-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, default=0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('reach', models.BooleanField(default=False, null=True)),
                ('depart', models.BooleanField(default=False, null=True)),
                ('arrive', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amb_assgn', models.BooleanField(default=False, null=True)),
                ('aid_assgn', models.BooleanField(default=False, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('performance', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency', models.BooleanField(default=False, null=True)),
                ('latitude', models.FloatField(blank=True, default=0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0, null=True)),
                ('doc', models.BooleanField(default=False, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('spl', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('performance', models.FloatField(blank=True, default=0, null=True)),
                ('assgn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aid.aid')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aid.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, default=0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0, null=True)),
                ('ais', models.BooleanField(default=False, null=True)),
                ('bis', models.BooleanField(default=False, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('hosp_assgn', models.BooleanField(default=False, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aid.driver')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aid.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='aid',
            name='ambulance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aid.ambulance'),
        ),
        migrations.AddField(
            model_name='aid',
            name='hospital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aid.hospital'),
        ),
    ]
