# Generated by Django 3.2.5 on 2021-10-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
