# Generated by Django 3.2.5 on 2021-10-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0002_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
