# Generated by Django 3.2.5 on 2021-10-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0003_alter_driver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='aid_latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='aid_longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
