# Generated by Django 3.2.5 on 2021-10-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0005_auto_20211026_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='aid_details',
        ),
        migrations.AddField(
            model_name='aid',
            name='aid_details',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
