# Generated by Django 3.2.5 on 2021-10-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0006_auto_20211026_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aid',
            name='ambulance',
        ),
        migrations.RemoveField(
            model_name='aid',
            name='hospital',
        ),
        migrations.AddField(
            model_name='ambulance',
            name='aid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aid.aid'),
        ),
    ]
