# Generated by Django 3.2.5 on 2021-10-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0007_auto_20211028_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aid.hospital'),
        ),
    ]
