# Generated by Django 3.2.5 on 2021-10-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0009_auto_20211028_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aid',
            name='status',
            field=models.CharField(choices=[('Ambulance Not assigned', 'Ambulance Not assigned'), ('Ambulance Assigned', 'Ambulance Assigned'), ('Ambulance Not Available', 'Ambulance Not Available'), ('Ambulance arrivingg', 'Ambulance arrivingg')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Aid Assigned', 'Aid Assigned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Contact', 'Contact')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=200, null=True),
        ),
    ]
