# Generated by Django 3.2.5 on 2021-10-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0011_auto_20211028_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='ambulance',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='hospital',
        ),
    ]
