# Generated by Django 3.2.5 on 2021-10-29 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0016_auto_20211030_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aid.driver'),
        ),
    ]
