# Generated by Django 3.2.5 on 2021-10-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0017_ambulance_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='aid_latitude',
        ),
        migrations.RemoveField(
            model_name='ambulance',
            name='aid_longitude',
        ),
    ]
