# Generated by Django 3.2.5 on 2021-10-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0020_auto_20211030_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aid',
            name='arrive',
        ),
        migrations.RemoveField(
            model_name='aid',
            name='depart',
        ),
        migrations.RemoveField(
            model_name='aid',
            name='reach',
        ),
    ]
